### ISSUE TITLE
Interdependent Tuning Parameters

### ISSUE THREAD

**Issue by ari-wwu** [jansel/opentuner#106]
Dear OpenTuner developers, 

we would like to test OpenTuner for auto-tuning the OpenCL GEMM kernel xgemm_direct that is part of the CLBlast library (https://github.com/CNugteren/CLBlast/tree/master/src/tuning/kernels). The kernel is special as its tuning parameters have various interdependencies (https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xgemm_direct.cpp#L119), for example, the loop unrolling tuning parameter has to divide the tile size tuning parameter, and the product of the thread group size tuning parameters in x- and y-dimension divided by the so-called re-shaped tile dimension parameter has to divide the tile size parameter, etc. 
Is it possible to auto tune such a kernel whose tuning parameters are interdependent with OpenTuner, and if so, how?

Many thanks in advance!

**Comment by jansel** [comment]
You can subclass ConfigurationManipulator or Parameter types to implement constraints like this.  Three different approaches come to mind:

1) Override [.normalize()](https://github.com/jansel/opentuner/blob/master/opentuner/search/manipulator.py#L42) to snap invalid configs to their closest valid config.

2) Create a new parameter type with extra constraints.  For an example see [PowerOfTwoParameter](
https://github.com/jansel/opentuner/blob/master/opentuner/search/manipulator.py#L808)

3) For many types of constraints, you can map your search space with constraints to one without constraints that are easier to search.  For example:

Suppose you have the parameters `A` and `B` the constraints that `A divides B`.  If you rewrite your parameters as:
`A = p1`
`B = p1 * p2`
Now you have two parameters `p1` and `p2` which can both be any positive integer without constraints between them.

**Comment by ari-wwu** [comment]
Thank you. I have a couple of questions regarding your points 1-3:

1) Can you please explain in more detail what the "closest valid config" is and how it can be computed? For example, in case of CLBlast's GEMM, the configuration

  WGD    = 406
  MDIMCD = 4
  NDIMCD = 120
  MDIMAD = 10
  NDIMBD = 57
  KWID   = 64
  VWMD   = 4
  VWND   = 1
  PADA   = 0
  PADB   = 1

is invalid because the following constraints are not satisfied:

- WGD % MDIMCD == 0
- WGD % NDIMCD == 0
- WGD % MDIMAD == 0
- WGD % ((MDIMCD * NDIMCD) / MDIMAD) == 0
- WGD % NDIMBD == 0
- (MDIMCD * NDIMCD) % NDIMBD == 0
- WGD % ((MDIMCD * NDIMCD) / NDIMBD) == 0
- WGD % KWID == 0
- (WGD / MDIMCD) % VWMD == 0

What is the closest valid configuration of this invalid configuration and how can it be computed?

2) Can you please provide an example of how a new parameter type has to be implemented for CLBlast GEMM's tile size tuning parameter WGD? It has to be a value from 1 to the input size N, and it has to be a multiple of the following parameters:
  - KWID
  - MDIMCD*VWMD (i.e., the product of two tuning parameters MDIMCD and VWMD)
  - NDIMCD*VWND
  - MDIAMD*VWMD
  - NDIMBD*VWND
  - (MDIMCD*NDIMCD)/MDIMAD (i.e., the product of two tuning parameters MDIMCD and NDIMCD, divided by the tuning parameter MDIMAD)
  - (MDIMCD*NDIMCD)/NDIMBD 
  
3) How would you define A and B if both have to be in a specific interval [1,N]?

**Comment by jansel** [comment]
There isn't a good general solution for any set of constraints.  This is an NP-hard problem.  One could create constraints that require solving SAT problems, factoring, etc.  In practice, most constraints encountered in program optimization can be addressed with heuristics or are small enough where you can brute force them.  For your problem, if 
`WGD` is prime the only legal values for most parameters are `1` and `WGD`.  You could force `WGD` to be compound by constructing it as a product of integer parameters, making it a power of 2, or factor it and rounding other parameters to the nearest factor in `normalize()`.   The best heuristic depends a lot on your search space.  You want a search space where most points make sense and also with good locality where similar configs are close together.  I'd suggest trying a few encodings and seeing what works best.

For 3, OpenTuner supports dynamic ranges for parameters if you override `param.legal_range(config)`.  The legal range of `p2` would be `1` to `N // p1`.  This would have a similar effect to just storing a new parameter `p2f` a float between 0 and 1 and computing `p2 = round(p2f * (N // p1 - 1)) + 1`.

**Comment by jbosboom** [comment]
OpenTuner doesn't require a perfectly precise description of the search space to be effective; it isn't a constraint solver.  It's more important that

- a reasonable number of the points in the space are "decent", so that when OpenTuner picks some random points to start the search (or during the search if the techniques are not paying off), at least one of them is in a region of the parameter space that isn't hopeless, and
- there's a path from one of those random starting points to the "best/very good" configuration that is not extremely complex, so that the techniques can make progress.

So when you're repairing an invalid configuration, you don't have to find the _closest_ valid configuration, just a reasonably nearby one.  You probably have some intuition about the relative importance of the parameters, so you can focus on maintaining those parameters' values, at the expense of changing other parameters more during the repair.  You should try to ensure that mutating a configuration usually results in a new configuration, rather than just being repaired back to the same configuration, so that techniques don't get stuck in local minima/maxima.

For your `WGD` parameter, I would instead use a multiplier integer parameter, and then derive the actual `WGD` value by multiplying that multiplier by the least common multiple of all the other things it has to be a multiple of, and then clamp the result to `[1, N]`.  The general takeaway is that the parameter space you present to OpenTuner doesn't have to be the parameter space consumed by your application; you have an opportunity to apply transformations when you're translating an OpenTuner configuration to whatever command-line/file format your application consumes when running trials.

**Comment by ari-wwu** [comment]
Many thanks for all the help. Everything you both said sounds very reasonable, however, it still remains unclear to me, whats the best way of using OpenTuner for auto-tuning CLBlast's GEMM. We are currently working on an own auto-tuning tool and want to make a fair comparison with OpenTuner. Our approach for auto-tuning GEMM with OpenTuner is to use the unconstrained search space (i.e., we ignore the parameters' interdependencies in the search space) and set a penalty value in case of invalid configurations (i.e., we return highest possible runtime in OpenTuner's "run" function). Do you think this is an appropriate way of using OpenTuner for CLBlast's GEMM?

**Comment by jbosboom** [comment]
No, I don't think it is.  I'm not sure OpenTuner would produce even one valid configuration in that setup, and even if it does, I wouldn't expect it to make progress.  If you think about the fitness landscape as a plot [like this](https://upload.wikimedia.org/wikipedia/commons/b/b7/Three-dimensional_graph.png) (but with more dimensions, of course), OpenTuner sees a few extremely tiny spikes of decent (valid) configurations, surrounded by a sea of badness (penalty).  OpenTuner is unlikely to find a spike to begin with, and even less likely to jump to another spike, because all OpenTuner learns from each trial is that something is bad, not how to fix it.  I do not expect OpenTuner's general tuning techniques to discover/work around divisibility constraints starting with no prior knowledge.

You can reject a configuration by setting the `ERROR` state on the result, but this is typically used when a configuration causes the system being tuned to crash, and is expected to be rare.  ([Here's how the PetaBricks tuner does it.](https://github.com/jansel/opentuner/blob/e8e81b67be496559b23cee657e0b37aab51c34df/examples/petabricks/pbtuner.py#L114)).  OpenTuner will just go ask the techniques for more configurations to try, but this way the techniques won't try to e.g. hill-climb based on the penalty values.  If you're rejecting most or all of the configurations generated, you may find that some techniques start generating duplicates (e.g., the genetic algorithms will exhaust the diversity of the current pool of individuals).  Basically I don't expect this to work either.

It sounds like you've tried at least the penalty-value approach already, though, so what happened?

I am also curious to know how much you've taught your tuner tool about the divisibility constraints.

**Comment by ari-wwu** [comment]
> You can reject a configuration by setting the ERROR state on the result, but this is typically used when a configuration causes the system being tuned to crash, and is expected to be rare. (Here's how the PetaBricks tuner does it.). OpenTuner will just go ask the techniques for more configurations to try, but this way the techniques won't try to e.g. hill-climb based on the penalty values. If you're rejecting most or all of the configurations generated, you may find that some techniques start generating duplicates (e.g., the genetic algorithms will exhaust the diversity of the current pool of individuals). Basically I don't expect this to work either.

We tried your suggested approach right now -- setting the ERROR state on the result, analogously to PetaBricks --  and get the same results as with our initial approach -- setting a penalty value.

> It sounds like you've tried at least the penalty-value approach already, though, so what happened?

Exactly that what you said: in case of many invalid configurations in the search space, OpenTuner is not able to find valid configurations.

>  I am also curious to know how much you've taught your tuner tool about the divisibility constraints.

We tell our tuner for each tuning parameter 1) its range of values, e.g., an interval [1,N], and 2) boolean functions that express the divisibility constraints.
