### ISSUE TITLE
Help with impact of chosen options

### ISSUE THREAD

**Issue by tdeneau** [jansel/opentuner#116]
I have been experimenting with the Java Auto Tuning Tool (JATT) which is layered on OpenTuner.  The resulting option set can be rather large.  I was wondering whether there is any info in log files or elsewhere that tells you which options had the biggest impact on performance.

**Comment by jbosboom** [comment]
OpenTuner doesn't attempt to do that.  It's quite hard to do when the search space has more than a few parameters due to interdependcies between parameters, especially because OpenTuner's techniques change multiple (possibly all) parameters simultaneously.

The database does store the configuration and result of each trial, so you can manually look at them (they're gzipped, pickled dictionaries, so writing some code is required), form hypotheses about what parameters are important, and run experiments.  But there's no automated support.
